---

dependencies:
  - role: docker
    docker_service_state: started
  - openshift
  - role: terraform
    terraform_source: https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
